# Site settings
title: 2ndfork (modular-gremlins)
author:
  name: Just Only Jon
  email: your-email@domain.com
description: "Liam's Blog"

# Build settings
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
